In [ ]:
paths = ["/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1A/Breakdown.csv", 
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1B/Breakdown.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1C/Breakdown.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1D/Breakdown.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1E/Breakdown.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1J/Breakdown.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1K/Breakdown.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1L/Breakdown.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 8J/Breakdown.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 8L/Breakdown.csv"]

In [18]:
import pandas as pd
import numpy as np
from scipy.sparse import vstack

data = []

for path in paths:
    temp = pd.read_csv(path)
    data.append(temp.iloc[:, :2].values)

merged = np.vstack(data)

df_breakdown = pd.DataFrame(
    merged,
    columns=pd.read_csv(paths[0]).columns[:2]
)
df_breakdown.columns = ["Collector_Emitter_Voltage_Vce", "Leakage_Current_Ic"]

df_breakdown

      Collector_Emitter_Voltage_Vce  Leakage_Current_Ic
0                          550.5270            0.000004
1                          551.0286            0.000004
2                          551.5306            0.000004
3                          552.0320            0.000004
4                          552.5338            0.000004
...                             ...                 ...
1985                       648.0370            0.000005
1986                       648.5394            0.000005
1987                       649.0406            0.000005
1988                       649.5410            0.000005
1989                       650.0424            0.000005

[1990 rows x 2 columns]

In [19]:
df_breakdown.to_csv("/Users/samarth/Documents/SIH 26/Final_Data/Breakdown.csv", index=False)

In [20]:
paths = ["/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1A/LeakageIV.csv", 
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1B/LeakageIV.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1C/LeakageIV.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1D/LeakageIV.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1E/LeakageIV.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1J/LeakageIV.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1K/LeakageIV.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1L/LeakageIV.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 8J/LeakageIV.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 8L/LeakageIV.csv"]

In [22]:
data = []

for path in paths:
    temp = pd.read_csv(path)
    data.append(temp.iloc[:, :2].values)

merged = np.vstack(data)

df_leakage = pd.DataFrame(
    merged,
    columns=pd.read_csv(paths[0]).columns[:2]
)
df_leakage.columns = ["Applied_Voltage", "Leakage_Current"]

df_leakage

      Applied_Voltage  Leakage_Current
0            4.013724     1.179669e-08
1            7.020895     1.821858e-08
2           10.066110     2.633379e-08
3           13.053110     3.403392e-08
4           16.061600     4.139143e-08
...               ...              ...
1985       587.999300     4.300729e-06
1986       590.989900     4.340944e-06
1987       594.033800     4.382679e-06
1988       597.042800     4.424245e-06
1989       600.050900     4.466115e-06

[1990 rows x 2 columns]

In [23]:
df_leakage.to_csv("/Users/samarth/Documents/SIH 26/Final_Data/LeakageIV.csv", index=False)

In [24]:
paths = ["/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1A/Turn On.csv", 
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1B/Turn On.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1C/Turn On.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1D/Turn On.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1E/Turn On.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1J/Turn On.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1K/Turn On.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 1L/Turn On.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 8J/Turn On.csv",
         "/Users/samarth/Documents/SIH 26/Dataset/IGBT-IRG4BC30K/Part 8L/Turn On.csv"]

In [25]:
data = []

for path in paths:
    temp = pd.read_csv(path)
    data.append(temp.iloc[:, :2].values)

merged = np.vstack(data)

df_turn_on = pd.DataFrame(
    merged,
    columns=pd.read_csv(paths[0]).columns[:2]
)
df_turn_on.columns = ["Gate_Voltage", "Collector_Current"]

df_turn_on

      Gate_Voltage  Collector_Current
0         2.020181       5.885971e-09
1         2.040083       5.927931e-09
2         2.060686       5.913162e-09
3         2.080598       5.896354e-09
4         2.100827       6.043535e-09
...            ...                ...
1985      5.205013       2.500231e-04
1986      5.205044       2.500240e-04
1987      5.205053       2.500234e-04
1988      5.205057       2.500221e-04
1989      5.205097       2.500241e-04

[1990 rows x 2 columns]

In [26]:
df_turn_on.to_csv("/Users/samarth/Documents/SIH 26/Final_Data/TurnOn.csv", index=False)